### ISSUE TITLE
When using "Characters" automatic type it will also consider non-characters/objects as characters

### ISSUE THREAD

**Issue by elreymu** [Jibaku789/sd-webui-deepdanbooru-tag2folder#2]
For example, if there's a star symbol , it will create a folder called "star_(symbol)"
because the tag has "(" in the name it will consider it as a character as it happens also with many others tags for example weapons such as "bow_(weapon)" and other common tags

Not sure how that can be fixed but in any case i would like a way to manually black list such tags to prevent it from creating a folder for unwanted tags.

**Comment by Jibaku789** [comment]
Fixed in latest upload
